name: Reset votes

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Build project
        run: |
          pip install -r requirements.txt
          python run.py 64d7526ad085590377fdf707